version: '3.7'

services:
  # stream_server:
  #   build: .
  #   ports:
  #     - "5433:5433"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stream_server
volumes:
  postgres_data:
networks:
  stream_server: